### ISSUE TITLE
bignum_from_string: only works with hex-strings w/ multiple of 8 characters

### ISSUE THREAD

**Issue by DEF7** [kokke/tiny-bignum-c#14]
The problem lies with this piece of code: https://github.com/kokke/tiny-bignum-c/blob/e814d2b6b522ecaa67701453c492811a8adbc555/bn.c#L108-L120

which appears as:

`
  int i = nbytes - (2 * WORD_SIZE); /* index into string */
  int j = 0;                        /* index into array */

  /* reading last hex-byte "MSB" from string first -> big endian */
  /* MSB ~= most significant byte / block ? :) */
  while (i >= 0)
  {
    tmp = 0;
    sscanf(&str[i], SSCANF_FORMAT_STR, &tmp);
    n->array[j] = tmp;
    i -= (2 * WORD_SIZE); /* step WORD_SIZE hex-byte(s) back in the string. */
    j += 1;               /* step one element forward in the array. */
  }
`

If 'i' (the length of the inbound string, in characters) is not a multiple of '2 * WORD_SIZE' then it will skip over the MSB hexadecimal characters at the beginning of the string when 'i < 0' and miss the characters at the beginning of the inbound string, incorrectly setting 'n'.

I think the use of sprintf/sscanf is not ideal. Custom to/from string routines would be better.

**Comment by kokke** [comment]
Hi @DEF7 and thanks for your interest in this project :)

You're correct that the to/from_string methods only works for a 8-bite chunks, but this is by design.

I only use the functions for the test-code, which I hint at in the readme: `**stdio.h is only used for testing functions parsing to and from hex-strings.**`. This is the reason for not implementing better to/from_string methods -- they are only used for the testing.

> Custom to/from string routines would be better.

I agree. I would most likely accept a PR that improved the current situation :)

**Comment by DEF7** [comment]
Ok. In the meantime I'll just pad the beginning of my hex strings with
zeroes which seems to work fine for now. Thanks!

**Comment by kokke** [comment]
Until further notice, I think it's fair to add this piece of assertion-code in `bignum_from_string`:

```C
require((nbytes % (sizeof(DTYPE) * 2)) == 0, "string length must be a multiple of (sizeof(DTYPE) * 2) characters");
```
,

... so that you at least get a proper failure/crash with a line number etc., if you mess up:

,
> test_hand_picked: bn.c:104: bignum_from_string: Assertion `(nbytes % (sizeof(uint16_t) * 2)) == 0 && "string length must be a multiple of (sizeof(DTYPE) * 2) characters"' failed.


What do you think @DEF7 ?
