### ISSUE TITLE
Word size=8?

### ISSUE THREAD

**Issue by bumbread** [kokke/tiny-bignum-c#31]
Current implementation of the header will throw a compile-time error, if word size would be defined to be 8. On x86_64 platforms, which are a very common target this word size might be the fastest type and thus it is desireable that WORD_SIZE=8 could also be specified

**Comment by kokke** [comment]
Hi @bumbread and thanks for your interest :)

The library depends on something larger than `DTYPE` to hold intermediate results: `DTYPE_TMP` (to check for overflow). In other words, the library already performs all operations in 64bit, but truncates results to 32 bits.

GCC has 128bit integers but that is non-standard, which is why the default is with 32bit `DTYPE` and 64 bit integers for `DTYPE_TMP`.
